# Generated by Django 5.0.6 on 2024-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amenity_name", models.CharField(max_length=100)),
                ("amenity_type", models.CharField(max_length=50)),
                ("room_type", models.CharField(max_length=50)),
                ("sort_key", models.IntegerField()),
            ],
        ),
    ]
