# Generated by Django 5.0.6 on 2024-09-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("room_type", models.CharField(max_length=100)),
                ("bed_type", models.CharField(max_length=100)),
                ("is_non_smoking", models.BooleanField(default=True)),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
